jasypt:
  encryptor:
    #1234567
    password: ${ENCRYPT_PASSWORD}

server:
  port: 8001
spring:
  profiles:
    active: dev
  application:
    name: chengw-config-server


---
spring:
  profiles: dev
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/veaxcw/chengw-config-repo.git
          username: ${git_username}
          password: ${git_password}
          search-paths: /{application}
          force-pull: true
          timeout: 1000
          refresh-rate: 10
#服务注册
eureka:
  instance:
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
#    将ip注册到Eureka server 上，不配置 则是主机名
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    #是否将自己注册到Eureka server
    register-with-eureka: true
    #是否从Eureka server获取注册信息
    fetch-registry: false
    service-url:
       defaultZone: http://127.0.0.1:8000/eureka/
  server:
    enable-self-preservation: false

#测试环境
---
spring:
  profiles: test
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/veaxcw/chengw-config-repo.git
          username: ${git_username}
          password: ${git_password}
          search-paths: /{application}
          force-pull: true
          timeout: 1000
          refresh-rate: 10
#服务注册
eureka:
  instance:
    #    将ip注册到Eureka server 上，不配置 则是主机名
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    #是否将自己注册到Eureka server
    register-with-eureka: true
    #是否从Eureka server获取注册信息
    fetch-registry: false
    service-url:
      defaultZone: http://47.93.19.130:8000/eureka/
  server:
    enable-self-preservation: false

